//'use-strict';

module.exports = {
commonItems : ['ID', 'keys', 'wallet', 'cell phone'],
extraItems : ['cash', 'credit card', 'car keys', 'home keys', 'office keys', 'umbrella', 'wrist watch'],

defaultPlaces : [

  {placeName: {genericName: 'work', specificName:''},       usualHour:9,    itemList: ["briefcase", "office ID", "pen", "laptop" ,"important files"], actionList: []},
  {placeName: {genericName: 'work', specificName:'office'}, usualHour:9,    itemList: ["briefcase", "office ID", "pen", "laptop" ,"important files"], actionList: []},
  {placeName: {genericName: 'work', specificName:'factory'},usualHour:9,    itemList: ["briefcase", "office ID", "pen", "laptop" ,"important files", 'helmet', 'protective shoes'], actionList: []},
  {placeName: {genericName: 'work', specificName:'bank'},   usualHour:9,    itemList: ["briefcase", "office ID", "pen", "laptop" ,"important files"], actionList: []},
  {placeName: {genericName: 'work', specificName:'shop'},   usualHour:9,    itemList: ['shop keys','pen', 'registers'], actionList: []},
  //{placeName: "work",      usualHour:9,    itemList: ["briefcase", "office ID", "pen", "laptop" ,"important files"], actionList: []},
  //{placeName: "duty",      usualHour:9,    itemList: ["briefcase", "office ID", "pen", "laptop" ,"important files"], actionList: []},


  {placeName: {genericName: 'classes', specificName:''},            usualHour:8,    itemList: ['college ID', 'college bag', 'pen', 'laptop', 'books'], actionList: []},
  {placeName: {genericName: 'classes', specificName:'college'},     usualHour:8,    itemList: ['college ID', 'college bag', 'pen', 'laptop', 'books', 'notes'], actionList: []},
  {placeName: {genericName: 'classes', specificName:'university'},  usualHour:8,    itemList: ['university ID', 'bag', 'pen', 'laptop', 'books', 'notes'], actionList: []},
  {placeName: {genericName: 'classes', specificName:'school'},      usualHour:8,    itemList: ['school ID', 'school bag', 'pencil box', 'laptop', 'books'], actionList: []},
  {placeName: {genericName: 'classes', specificName:'tution'},      usualHour:8,    itemList: ['bag', 'pen', 'books'], actionList: []},
  {placeName: {genericName: 'classes', specificName:'exams'},       usualHour:8,    itemList: ['bag', 'pen', 'books'], actionList: ['Best of luck']},
  {placeName: {genericName: 'classes', specificName:'viva'},        usualHour:8,    itemList: ['bag', 'pen', 'books'], actionList: []},
  {placeName: {genericName: 'classes', specificName:'practicals'},  usualHour:8,    itemList: ['bag', 'pen', 'books'], actionList: []},
  {placeName: {genericName: 'classes', specificName:'trials'},      usualHour:8,    itemList: ['bag', 'equipments', 'water'], actionList: ['Best of luck']},
  {placeName: {genericName: 'classes', specificName:'tryouts'},     usualHour:8,    itemList: ['bag', 'water', 'strength'], actionList: []},
  {placeName: {genericName: 'classes', specificName:'nursery'},     usualHour:8,    itemList: ['tiffin box', 'water bottle', 'lunch', 'crayons', 'toys'], actionList: []},


  {placeName: {genericName: 'practice', specificName:'sport'},      usualHour:8,    itemList:   ['practice kit', 'practice clothes'], actionList: []},
  {placeName: {genericName: 'practice', specificName:'football'},   usualHour:8,    itemList:   ['suitable short for hot weather', 'dry-fit shirts', 'girdle', 'helmet', 'shoulder pads',
                                                                                                'mouth piece for breathing', 'water bottle', 'first aid kit', 
                                                                                                'tissues', 'wet wipes'], actionList: ['parents for emotional support']},
  {placeName: {genericName: 'practice', specificName:'golf'},       usualHour:8,    itemList:   ['new golf balls', 'old golf balls', 'multiple golf gloves', 'rain gear', 'umbrella',
                                                                                                'tees', 'towel',  'writing utensils including a pencil, pen, and sharpie', 'ball markers',
                                                                                                'sun screen and bug spray', 'water bottle', 'rules book', 'snacks', 'first aid kit',
                                                                                                'tissues', 'wet wipes'], actionList: []},
  {placeName: {genericName: 'practice', specificName:'volleyball'}, usualHour:8,    itemList:   ['bag', 'practice clothes', 'shoes'], actionList: ['Sunny beaches are great fun!']},
  {placeName: {genericName: 'practice', specificName:'basketball'}, usualHour:8,    itemList:   ['basketball shoes', 'court grip', 'instant cold pack', 'mouth guards', 'first aid kit', 
                                                                                                 'tissues', 'wet wipes'], actionList: []},
  {placeName: {genericName: 'practice', specificName:'running'},    usualHour:8,    itemList:   ['running shoes', 'technical fabric running clothes', 'running socks', 'water', 
                                                                                                 'sun protection', 'health tracker', 'music'], actionList: []},
  {placeName: {genericName: 'practice', specificName:'run'},        usualHour:8,    itemList:   ['running shoes', 'technical fabric running clothes', 'running socks', 'water', 
                                                                                                 'sun protection', 'health tracker', 'music'], actionList: []},
  {placeName: {genericName: 'practice', specificName:'jogging'},    usualHour:8,    itemList:   ['running shoes', 'technical fabric running clothes', 'running socks', 'water', 
                                                                                                 'sun protection', 'health tracker', 'music'], actionList: []},
  {placeName: {genericName: 'practice', specificName:'jog'},        usualHour:8,    itemList:   ['running shoes', 'technical fabric running clothes', 'running socks', 'water', 
                                                                                                 'sun protection', 'health tracker', 'music'], actionList: []},

  {placeName: {genericName: 'practice', specificName:'cricket'},    usualHour:8,    itemList: ['bag', 'practice clothes', 'bat', 'ball', 'guards', 'helmet', 'ankle pad', 'leg pads'], actionList: []},
  {placeName: {genericName: 'practice', specificName:'hockey'},     usualHour:8,    itemList: ['bag', 'practice clothes', 'hockey', 'pad', 'shoes'], actionList: []},
  {placeName: {genericName: 'practice', specificName:'swimming'},   usualHour:8,    itemList: ['membership card', 'swim suit', 'goggles', 'swim cap', 'towel', 'shampoo', 'conditioner', 'comb', 'flip flops'], actionList: []},

  {placeName: {genericName: 'practice', specificName:'music'},      usualHour:8,    itemList: ['bag', 'musical instrument'], actionList: []},
  {placeName: {genericName: 'practice', specificName:'sport'},      usualHour:8,    itemList: ['bag', 'practice clothes', 'practice shoes'], actionList: []},

  {placeName: {genericName: 'chores', specificName:'laundry'},      usualHour:8,    itemList: ['laundry bags', 'detergent', 'fabric softener', 'dryer sheets', 'hand sainitizers', 'coins or card', 'book or magazine'], actionList: []},
  {placeName: {genericName: 'chores', specificName:'laundromat'},   usualHour:8,    itemList: ['laundry bags', 'detergent', 'fabric softener', 'dryer sheets', 'hand sainitizers', 'coins or card', 'book or magazine'], actionList: []},

  {placeName: {genericName: 'out', specificName:'restaurant'},    usualHour:9,    itemList: ['cash'], actionList: []},
  {placeName: {genericName: 'out', specificName:'bank'},          usualHour:9,    itemList: ['cash', 'bank documents'], actionList: []},
  {placeName: {genericName: 'out', specificName:'breakfast'},     usualHour:9,    itemList: ['cash'], actionList: []},
  {placeName: {genericName: 'out', specificName:'brunch'},        usualHour:9,    itemList: ['cash'], actionList: []},
  {placeName: {genericName: 'out', specificName:'lunch'},         usualHour:9,    itemList: ['cash'], actionList: []},
  {placeName: {genericName: 'out', specificName:'snacks'},        usualHour:9,    itemList: ['cash'], actionList: []},
  {placeName: {genericName: 'out', specificName:'dinner'},        usualHour:9,    itemList: ['cash'], actionList: ['Don\'t forget your favorite sports jacket']},
  {placeName: {genericName: 'out', specificName:'cafe'},          usualHour:9,    itemList: ['cash'], actionList: []},
  {placeName: {genericName: 'out', specificName:'mall'},          usualHour:9,    itemList: ['cash'], actionList: []},
  {placeName: {genericName: 'out', specificName:'shopping'},      usualHour:9,    itemList: ['cash'], actionList: []},
  {placeName: {genericName: 'out', specificName:'shop'},          usualHour:9,    itemList: ['cash'], actionList: []},
  {placeName: {genericName: 'out', specificName:'movie'},         usualHour:9,    itemList: ['cash', 'a suitable partner'], actionList: []},
  {placeName: {genericName: 'out', specificName:'drama'},         usualHour:9,    itemList: ['cash', 'a suitable partner'], actionList: []},
  {placeName: {genericName: 'out', specificName:'concert'},       usualHour:9,    itemList: ['cash', 'a suitable partner'], actionList: []},
  {placeName: {genericName: 'out', specificName:'rock concert'},  usualHour:9,    itemList: ['cash', 'a suitable partner'], actionList: []},
  {placeName: {genericName: 'out', specificName:'play'},          usualHour:9,    itemList: ['cash', 'a suitable partner'], actionList: []},
  {placeName: {genericName: 'out', specificName:'drive'},         usualHour:9,    itemList: ['cash', 'car keys'], actionList: []},
  {placeName: {genericName: 'out', specificName:'long drive'},    usualHour:9,    itemList: ['cash', 'car keys'], actionList: []},
  {placeName: {genericName: 'out', specificName:'ride'},          usualHour:9,    itemList: ['cash', 'car keys'], actionList: []},
  {placeName: {genericName: 'out', specificName:'amusement park'},usualHour:9,    itemList: ['cash', 'membership card'], actionList: ['play safe']},
  {placeName: {genericName: 'out', specificName:'park'},          usualHour:9,    itemList: ['cash'], actionList: ['avoid strangers']},
  {placeName: {genericName: 'out', specificName:'walk'},          usualHour:9,    itemList: ['walking shoes'], actionList: []},
  {placeName: {genericName: 'out', specificName:'stroll'},        usualHour:9,    itemList: ['walking shoes'], actionList: []},
  {placeName: {genericName: 'out', specificName:'daily walk'},    usualHour:9,    itemList: ['walking stick', 'shoes'], actionList: []},
  {placeName: {genericName: 'out', specificName:'playground'},    usualHour:9,    itemList: ['cash'], actionList: ['Avoid strangers']},
  {placeName: {genericName: 'out', specificName:'friend\'s home'},usualHour:9,    itemList: ['cash'], actionList: ['Don\'t forget to inform parents']},
  {placeName: {genericName: 'out', specificName:'date'},          usualHour:9,    itemList: ['hankie', 'umbrella', 'sports jacket', 'lipstick', 'mouth freshner', 'body mist or perfume', 
                                                                                            'some cash', 'pepper spray, for just in case','ID', 'keys', 'wallet', 'cell phone'], actionList: ['You are looking beautiful']},
  {placeName: {genericName: 'out', specificName:'gym'},          usualHour:9,    itemList: ['membership card', 'workout clothes', 'work out bag', 'gym towel', 'trainers', 'jump rope', 'wrist wraps', 'yoga mat'], actionList: []},
//  {placeName: {genericName: 'out', specificName:'health'},          usualHour:9,    itemList: ['membership card', 'workout clothes', 'work out bag', 'gym towel', 'trainers', 'jump rope', 'wrist wraps', 'yoga mat'], actionList: []},



  {placeName: {genericName: 'party', specificName:''},            usualHour:9,    itemList: ['cash', 'gift'], actionList: ['don\'t forget to inform parents']},
  {placeName: {genericName: 'party', specificName:'friend\'s'},   usualHour:9,    itemList: ['cash'], actionList: ['don\'t forget to inform parents']},
  {placeName: {genericName: 'party', specificName:'house'},       usualHour:9,    itemList: ['cash'], actionList: ['don\'t forget to inform parents','be safe']},
  {placeName: {genericName: 'party', specificName:'cruise'},      usualHour:9,    itemList: ['cash', 'tickets', 'tuxedo'], actionList: []},
  {placeName: {genericName: 'party', specificName:'beach'},       usualHour:9,    itemList: ['lingerie', 'towels', 'sunscreen', 'volleyball'], actionList: []},
  {placeName: {genericName: 'party', specificName:'slumber'},     usualHour:9,    itemList: ['a good book'], actionList: ['don\'t forget to inform parents']},
  {placeName: {genericName: 'party', specificName:'homecoming'},  usualHour:9,    itemList: ['cash','limousine', 'mouth freshner', 'deodrant'], actionList: []},
  {placeName: {genericName: 'party', specificName:'bachelor'},    usualHour:9,    itemList: ['lots of cash', 'booking confirmations', 'booze', 'friends'], actionList: []},
  {placeName: {genericName: 'party', specificName:'bachelorette'},usualHour:9,    itemList: ['lots of cash', 'booking confirmations', 'booze', 'friends', 'matching dress for each day'], actionList: []},
  {placeName: {genericName: 'party', specificName:'baby shower'}, usualHour:9,    itemList: ['cash','gift'], actionList: []},
  {placeName: {genericName: 'party', specificName:'birthday'},    usualHour:9,    itemList: ['cash','gifts','birthday card'], actionList: []},
  {placeName: {genericName: 'party', specificName:'engagement'},  usualHour:9,    itemList: ['cash','gift'], actionList: []},
  {placeName: {genericName: 'party', specificName:'wedding'},     usualHour:9,    itemList: ['cash','gift'], actionList: []},
  {placeName: {genericName: 'party', specificName:'housewarming'},usualHour:9,    itemList: ['cash','gift'], actionList: []},
  {placeName: {genericName: 'party', specificName:'funeral'},     usualHour:9,    itemList: ['cash','baked product'], actionList: []},
  {placeName: {genericName: 'party', specificName:'anniversary'}, usualHour:9,    itemList: ['cash','gift'], actionList: []},


//  {placeName: {genericName: 'club', specificName:''},          usualHour:9,    itemList: ['membership card'], actionList: []},
  

  
  {placeName: {genericName: 'checkup', specificName:''},          usualHour:9,    itemList: ['cash', 'previous checkup reports', 'lab test reports', 'regular prescriptions', 'insurance details'], actionList: []},
  {placeName: {genericName: 'checkup', specificName:'doctor'},    usualHour:9,    itemList: ['cash', 'previous checkup reports', 'lab test reports', 'regular prescriptions', 'insurance details'], actionList: ['Please confirm your appointment before going']},
  {placeName: {genericName: 'checkup', specificName:'hospital'},  usualHour:9,    itemList: ['cash', 'previous checkup reports', 'lab test reports', 'regular prescriptions', 'insurance details'], actionList: ['Please confirm your appointment before going']},
  {placeName: {genericName: 'checkup', specificName:'specialist'},usualHour:9,    itemList: ['cash', 'previous checkup reports', 'lab test reports', 'regular prescriptions', 'insurance details'], actionList: ['Please confirm your appointment before going']},
  {placeName: {genericName: 'checkup', specificName:'dentist'},   usualHour:9,    itemList: ['cash', 'previous checkup reports', 'lab test reports', 'regular prescriptions', 'insurance details'], actionList: ['Please confirm your appointment before going']},


  {placeName: {genericName: 'meeting', specificName:'interview'},     usualHour:9,    itemList: ['formal attire', 'mouth freshner','credentials', 'marksheets', 'experience certificates', 'résumé'], actionList: ['Don\'t forget to carry your confidence']},
  {placeName: {genericName: 'meeting', specificName:'job interview'}, usualHour:9,    itemList: ['formal attire', 'mouth freshner','credentials', 'marksheets', 'experience certificates', 'résumé'], actionList: ['Don\'t forget to carry your confidence']},
  {placeName: {genericName: 'meeting', specificName:'presentation'},  usualHour:9,    itemList: ['formal attire', 'mouth freshner','credentials', 'marksheets', 'experience certificates', 'résumé'], actionList: ['Don\'t forget to carry your confidence']},
  {placeName: {genericName: 'meeting', specificName:'client meeting'},usualHour:8,    itemList: ['formal attire', 'mouth freshner','project files'], actionList: []},


  {placeName: {genericName: 'short travel', specificName:''},                 usualHour:9,    itemList: ['cash', 'check tickets'], actionList: ['Don\'t forget to inform parents']},
  {placeName: {genericName: 'short travel', specificName:'hotel'},            usualHour:9,    itemList: ['cash', 'check tickets'], actionList: ['Don\'t forget to inform parents']},
  {placeName: {genericName: 'short travel', specificName:'Airport'},          usualHour:9,    itemList: ['cash', 'check tickets'], actionList: ['Don\'t forget to inform parents']},
  {placeName: {genericName: 'short travel', specificName:'railway station'},  usualHour:9,    itemList: ['cash', 'check tickets'], actionList: ['Don\'t forget to inform parents']},
  {placeName: {genericName: 'short travel', specificName:'bus stop'},         usualHour:9,    itemList: ['cash', 'check tickets'], actionList: ['Don\'t forget to inform parents']},
  {placeName: {genericName: 'short travel', specificName:'subway'},           usualHour:9,    itemList: ['cash', 'check tickets'], actionList: ['Don\'t forget to inform parents']},
  {placeName: {genericName: 'short travel', specificName:'metro'},            usualHour:9,    itemList: ['cash', 'check tickets'], actionList: ['Don\'t forget to inform parents']},

  {placeName: {genericName: 'tour', specificName:''},          usualHour:9,       itemList: ['passport', 'credentials', 'cash', 'credit card', 'frequent flyer card', 'reservations', 
                                                                                            'itineraries', 'hotel contact', 'cell phone', 'charger', 
                                                                                            'headphones', 'laptop', 'iPad', 'e-book reader', 'Belt', 'umbrella', 'sleepwear', 
                                                                                            'undergarments', 'eye wear', 'travel pillow', 'books', 'water bottle',
                                                                                            'ear plugs', 'Toothbrush', 'toothpaste', 'floss', 'mouthwash', 'Deodorant', 'shampoo', 
                                                                                            'conditioner', 'hair brush', 'hand sanitizer', 'night cream', 'shaving kit',
                                                                                            'facial tissues', 'travel towel', 'medical prescriptions', 'medicines'], 
                                                                               actionList: ['Arrange for care of pets, lawn, and plants', 
                                                                                            'Empty refrigerator of the items that will expire', 'Unplug appliances', 'Turn off taps',
                                                                                            'Lock all doors and windows','Set up timed light system']},
  {placeName: {genericName: 'tour', specificName:'official trip'},          usualHour:9,       itemList: ['passport', 'credentials', 'cash', 'credit card', 'frequent flyer card', 'reservations', 
                                                                                            'itineraries', 'hotel contact', 'cell phone', 'charger', 
                                                                                            'headphones', 'laptop', 'iPad', 'e-book reader', 'Belt', 'umbrella', 'sleepwear', 
                                                                                            'undergarments', 'eye wear', 'travel pillow', 'books', 'water bottle',
                                                                                            'ear plugs', 'Toothbrush', 'toothpaste', 'floss', 'mouthwash', 'Deodorant', 'shampoo', 
                                                                                            'conditioner', 'hair brush', 'hand sanitizer', 'night cream', 'shaving kit',
                                                                                            'facial tissues', 'travel towel', 'medical prescriptions', 'medicines'], 
                                                                               actionList: ['Arrange for care of pets, lawn, and plants', 
                                                                                            'Empty refrigerator of the items that will expire', 'Unplug appliances', 'Turn off taps',
                                                                                            'Lock all doors and windows','Set up timed light system']},                                                                                            

  {placeName: {genericName: 'long travel', specificName:'piligrimage'},usualHour:9,    itemList: ['passport', 'visa', 'credentials', 'cash', 'credit card', 'frequent flyer card', 'reservations', 
                                                                                            'itineraries', 'hotel contact', 'emergency contact', 'guide book', 'map', 'cell phone', 'charger', 
                                                                                            'headphones', 'camera', 'laptop', 'iPad', 'e-book reader', 'lightweight clothing', 'sweaters',
                                                                                            'T-shirt', 'Pants or shorts', 'Belt', 'Socks', 'walking shoes', 'umbrella', 'sleepwear', 
                                                                                            'undergarments', 'sunglasses', 'eye wear', 'Cap', 'swimsuit', 'travel pillow', 'books', 'water bottle',
                                                                                            'eye mask', 'ear plugs', 'Toothbrush', 'toothpaste', 'floss', 'mouthwash', 'Deodorant', 'shampoo', 
                                                                                            'conditioner', 'hair brush', 'hand sanitizer', 'sun screen', 'face mask', 'night cream', 'shaving kit',
                                                                                            'facial tissues', 'travel towel', 'medical prescriptions', 'medicines'], 
                                                                               actionList: ['Have the post office hold your mail', 'Stop newspaper delivery', 
                                                                                            'Arrange for care of pets, lawn, and plants', 'Pre-pay your bills', 
                                                                                            'Prearrange school absences for children and get any home study assignments required', 
                                                                                            'Empty refrigerator of the items that will expire', 'Unplug appliances','Turn off taps',
                                                                                            'Lock all doors and windows','Set up timed light system','Store valuables in a safe place',
                                                                                            'Leave house key and trip itinerary with a trusted friend']},

  {placeName: {genericName: 'long travel', specificName:'hajj'}, usualHour:9,    itemList: ['passport', 'visa', 'credentials', 'cash', 'credit card', 'frequent flyer card', 'reservations', 
                                                                                            'itineraries', 'hotel contact', 'emergency contact', 'guide book', 'map', 'cell phone', 'charger', 
                                                                                            'headphones', 'camera', 'laptop', 'iPad', 'e-book reader', 'lightweight clothing', 'sweaters',
                                                                                            'T-shirt', 'Pants or shorts', 'Belt', 'Socks', 'walking shoes', 'umbrella', 'sleepwear', 
                                                                                            'undergarments', 'sunglasses', 'eye wear', 'Cap', 'swimsuit', 'travel pillow', 'books', 'water bottle',
                                                                                            'eye mask', 'ear plugs', 'Toothbrush', 'toothpaste', 'floss', 'mouthwash', 'Deodorant', 'shampoo', 
                                                                                            'conditioner', 'hair brush', 'hand sanitizer', 'sun screen', 'face mask', 'night cream', 'shaving kit',
                                                                                            'facial tissues', 'travel towel', 'medical prescriptions', 'medicines'], 
                                                                               actionList: ['Have the post office hold your mail', 'Stop newspaper delivery', 
                                                                                            'Arrange for care of pets, lawn, and plants', 'Pre-pay your bills', 
                                                                                            'Prearrange school absences for children and get any home study assignments required', 
                                                                                            'Empty refrigerator of the items that will expire', 'Unplug appliances','Turn off taps',
                                                                                            'Lock all doors and windows','Set up timed light system','Store valuables in a safe place',
                                                                                            'Leave house key and trip itinerary with a trusted friend']},

  {placeName: {genericName: 'abroad', specificName:''},          usualHour:9,    itemList: ['passport', 'visa', 'credentials', 'cash', 'credit card', 'frequent flyer card', 'reservations', 
                                                                                            'itineraries', 'hotel contact', 'emergency contact', 'guide book', 'map', 'cell phone', 'charger', 
                                                                                            'headphones', 'camera', 'laptop', 'iPad', 'e-book reader', 'lightweight clothing', 'sweaters',
                                                                                            'T-shirt', 'Pants or shorts', 'Belt', 'Socks', 'walking shoes', 'umbrella', 'sleepwear', 
                                                                                            'undergarments', 'sunglasses', 'eye wear', 'Cap', 'swimsuit', 'travel pillow', 'books', 'water bottle',
                                                                                            'eye mask', 'ear plugs', 'Toothbrush', 'toothpaste', 'floss', 'mouthwash', 'Deodorant', 'shampoo', 
                                                                                            'conditioner', 'hair brush', 'hand sanitizer', 'sun screen', 'face mask', 'night cream', 'shaving kit',
                                                                                            'facial tissues', 'travel towel', 'medical prescriptions', 'medicines'], 
                                                                               actionList: ['Have the post office hold your mail', 'Stop newspaper delivery', 
                                                                                            'Arrange for care of pets, lawn, and plants', 'Pre-pay your bills', 
                                                                                            'Prearrange school absences for children and get any home study assignments required', 
                                                                                            'Empty refrigerator of the items that will expire', 'Unplug appliances','Turn off taps',
                                                                                            'Lock all doors and windows','Set up timed light system','Store valuables in a safe place',
                                                                                            'Leave house key and trip itinerary with a trusted friend']},                                                                         

  {placeName: {genericName: 'vacation', specificName:''},          usualHour:9,    itemList: ['passport', 'visa', 'credentials', 'cash', 'credit card', 'frequent flyer card', 'reservations', 
                                                                                            'itineraries', 'hotel contact', 'emergency contact', 'guide book', 'map', 'cell phone', 'charger', 
                                                                                            'headphones', 'camera', 'laptop', 'iPad', 'e-book reader', 'lightweight clothing', 'sweaters',
                                                                                            'T-shirt', 'Pants or shorts', 'Belt', 'Socks', 'walking shoes', 'umbrella', 'sleepwear', 
                                                                                            'undergarments', 'sunglasses', 'eye wear', 'Cap', 'swimsuit', 'travel pillow', 'books', 'water bottle',
                                                                                            'eye mask', 'ear plugs', 'Toothbrush', 'toothpaste', 'floss', 'mouthwash', 'Deodorant', 'shampoo', 
                                                                                            'conditioner', 'hair brush', 'hand sanitizer', 'sun screen', 'face mask', 'night cream', 'shaving kit',
                                                                                            'facial tissues', 'travel towel', 'medical prescriptions', 'medicines'], 
                                                                               actionList: ['Have the post office hold your mail', 'Stop newspaper delivery', 
                                                                                            'Arrange for care of pets, lawn, and plants', 'Pre-pay your bills', 
                                                                                            'Prearrange school absences for children and get any home study assignments required', 
                                                                                            'Empty refrigerator of the items that will expire', 'Unplug appliances','Turn off taps',
                                                                                            'Lock all doors and windows','Set up timed light system','Store valuables in a safe place',
                                                                                            'Leave house key and trip itinerary with a trusted friend']},


  
  

  {placeName: {genericName: 'supernatural', specificName:'heaven'},  usualHour:8,    itemList: [], actionList: ['loads of good deed is the prime requirement']},
  {placeName: {genericName: 'supernatural', specificName:'hell'},    usualHour:8,    itemList: [], actionList: ['well the place is not recommended by many']},



]

};
